### ISSUE TITLE
Change to machine-readable format

### ISSUE THREAD

**Issue by mre** [analysis-tools-dev/dynamic-analysis#21]
We'd like to include the tools in this repository on our [website for analysis tools](https://analysis-tools.dev/).
To make this happen, the tools would have to be machine-readable.

The structure should be similar to the [static-analysis repository](https://github.com/analysis-tools-dev/static-analysis/tree/master).
As a first step, every tool has to be moved into a separate `yml` file in the `data/tools` subfolder with the following structure:

```yml
name: toolname
tags:
  - c
  - rust
  - python
  - binary
license: Some license (e.g. MIT License)
types:
  - cli
source: 'https://github.com/example/toolname'
homepage: 'https://example.com'
description: 'Tool description goes here'
```

Some notes on the fields:
* The `tags` should be the languages that this tool supports (e.g. "c", "rust", "python" and "binary")
* `types`: how to run this tool. Can be `cli`, `service` (for webservices), or `ide-plugin`.
* source (optional): link to source code

For comparison, here is the same folder for `static-analysis`: https://github.com/analysis-tools-dev/static-analysis/tree/master/data/tools

The task is to create files for each tool. This can be done manually or with a script that parses the existing `README.md` and creates the `yml` files from it. After that we can use a generator (from [here](https://github.com/analysis-tools-dev/static-analysis/tree/master/data/render)) for the automatic `README.md` generation.
